name: Deploy With Docker to AWS Server
# 실행조건
on:
  push:
    branches:
      - main # main commit and push = [main,master]
jobs:
  deploy:
    # GitHub Actions가 제공하는 Ubuntu환경에서 실행
    # AWS EC2가 아니고 GitHub Actions에서 제공하는 임시로 사용하는 Ubuntu 환경에서 돌아가라고 설정
    runs-on: ubuntu-latest

    # 실행 순서 지정
    steps:
     #코드 체크 
     - name: Checkout:repository
       uses: actions/checkout@v4
     #JDK 설정 => SpringBoot 프로젝트를 build하기위해 jdk설정
     - name: SetUp JDK 21
       uses: actions/setup-java@v1
       with:
         distribution: 'temurin' # 가벼운 버전의 jdk를 사용하라고 지정
         java-version: '21'
     # 환경설정
     # DB 환경설정

     # Gradlew 권한 부여 
     - name: Set gradlew permission
       run: |
         chmod +x ./gradlew
     # Gradle Build 
     - name: Build with Gradlew
       run: ./gradlew clean build -x test
     # Docker hub 연결
     - name: Login DockerHub
       run: |
         echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
     - name: Build Docker Image
       run: |
         docker build -t "${{secrets.DOCKER_USERNAME}}"/last-app:latest .
     # DockerHub에 올림
     - name: Push Docker Image
       run: |
         docker push "${{secrets.DOCKER_USERNAME}}"/last-app:latest
     # AWS 연결 
     - name: Set SSH key Permission
       run: |
         mkdir -p ~/.ssh
         echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
     # ADD SSH Key 
     - name: Add SSH Key 
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
     # 서버 키 확인
     - name: Add Known_hosts
       run: |
         ssh-keyscan -H 13.125.234.82 >> ~/.ssh/known_hosts
     # 환경 설정 파일 생성
     - name: DB environment setting
       run: |
         ssh ubuntu@13.125.234.82 << EOF
           mkdir -p ~/app
           cd ~/app
           rm -f .env
           echo "DB_URL=${{secrets.DB_URL}}" >> ~/app/.env
           echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> ~/app/.env
           echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ~/app/.env
           chmod 600 ~/app/.env
         EOF
     # Deploy on Server DockerHub Image using
     - name: DockerHub image using
       run: |
         ssh ubuntu@13.125.234.82 << 'EOF'
           docker stop last-app || true
           docker rm last-app || true
           docker pull "${{secrets.DOCKER_USERNAME}}"/last-app:latest
           docker run -d --name last-app --env-file ~/app/.env -p 9090:9090 "${{secrets.DOCKER_USERNAME}}"/last-app:latest
         EOF
